# PIR
PIR_PIN = D35
# ULTRASUONI
TRIG_FS = D27
ECHO_FS = D26
TRIG_WS = D25
ECHO_WS = D33
# CELLA DI CARICO
LC_DT = D21
LC_SCK = D22
# ARDUCAM
CAM_CS = D5
CAM_SCK = D18
CAM_MISO = D19
CAM_MOSI = D23
CAM_SCL = D17
CAM_SDA = D16
# SERVO
SERVO_PIN = D3
# WATER LEVEL SENSOR
WL_SENS = D39 
WL_POW = D13 
# POMPA IDRAULICA (non testato)
PUMP = D15