# PIR
PIR_PIN = D35
# ULTRASUONI
TRIG_FS = D27
ECHO_FS = D26
TRIG_WS = D25
ECHO_WS = D33
# CELLA DI CARICO
LC_DT = D21
LC_SCK = D22
#LC_DT = D36 # testati
#LC_SCK = D34
# fotocamera testati 
CAM_CS = D5
CAM_SCK = D18
CAM_MISO = D19
CAM_MOSI = D23
CAM_SCL = D17
CAM_SDA = D16
# testato
SERVO_PIN = D3
WL_SENS = D39 # testato 
WL_POW = D13 # testato 
# non testato
PUMP = D15